### ISSUE TITLE
Option to have the layout start from the top left corner

### ISSUE THREAD

**Issue by martinmr** [flipcoder/midimech#1]
So I was today years old when I realized that you can have a negative offset in the linnstrument (go to global settings > row offset > hold octave + > select -5 in the screen that appears). So this means the lowest note is in the top left corner and the highest note is in the bottom right corner. With the default layout, chords become a lot easier because they fall where the fingers naturally want to go. Basic minor and major chords become trivial. 7ths are still a little bit awkward but much less than with the default layout.

So I haven't tried your software because I saw there are some issues with the 200 version, but I was wondering what happens to the chord shapes in your layout if you similarly start from the top left corner.

**Comment by flipcoder** [comment]
Midimech uses the "no overlap" mode and remaps the positions inside the software itself.  Supporting custom layouts is on my TODO list and I welcome experimentation.  You could take the cheat sheet in an image editor and vertically flip it to see how an inversion would look, but I don't see much of a benefit in doing that here.  With mech you have your thumbs available for lower notes, which is typically in the octaves where you want less notes anyway, such as holding a single note beneath a chord.  In my opinion, the awkwardness of +5 goes away on mech since the scales and chords are grouped in a way that is much easier to deal with both musically and ergonomically.

As for 200 support, past versions have been tested by others but until I hit a stable release it won't get tested immediately or in a way that is as thorough every iteration, so it's possible something may break and you'd need to rollback your version.  I'm hoping to get a LinnStrument 200 eventually but it may not happen for a while.  In the meantime I will hope for more testers.

**Comment by martinmr** [comment]
Sounds good. In that case, I'll wait for the custom layout support and try it on my own.
