### ISSUE TITLE
Other layouts possible?

### ISSUE THREAD

**Issue by martinmr** [flipcoder/midimech#2]
I was wondering how much it'd be to have more the option for more than one layout. Your software looks good, and I rather not redo the work to get my preferred layout working.

Specifically, I was thinking of this: https://www.le-nouveau-clavier.fr/english/#1a-new-evolution-of-the-keyboard-is-still-possible-or-the-grand-return-of-the-symmetrical-piano

So it's two whole tone scales, the bottom one starting at c and the top starting at c#. The resulting layout is isomorphic. Given that there are 8 rows in the linnstrument, this pattern could be repeated four times on top of each other, shifted by 2 octaves each time, so there's no overlap. This arrangement would cover 8 octaves in the 200 model. So it'd be like having four pianos stacked on top of each other, with the benefit of an isomorphic layout. The layouts could be shifted by one octave as well, so that octaves are two squares above.

To be honest, I find all the layouts I've seen so far deficient due to the ergonomics of the linnstrument. Anything that requires a lot of vertical movement is going against the natural angles of the wrists. Not an issue if one could hold it like a guitar, which I've tried but is not exactly ergonomic either. And I own an eight-string guitar also tuned in fourths like my linnstrument, and it's a world of difference. So I am wondering if this layout could be an answer to have a more horizontal way of playing while keeping the isomorphic properties of the linnstrument. The main disadvantage mentioned in the article is getting lost due to the symmetry, but this issue is not an issue with the linnstrument because of the LED lights.

**Comment by flipcoder** [comment]
Yeah multiple layouts are planned to be supported.  I've heard of this and I do like the Janko layout, but I think Mech is better.  You can get someone who doesn't know anything about music to stack a bunch of triangles and have them play beautiful piano runs.  I don't know of another layout that can do something like that.  It's hard to explain how easy it is if you haven't tried it.  I'm working on a youtube video right now that will go over its benefits and techniques and demonstrate more of it.

**Comment by martinmr** [comment]
How hard is it on the wrists? That's what's mostly worried about. With the default layout, it's not too hard when arpeggiating chords, but it's awful when trying to hold the chord.

I looked at the Janko layout, I think it's exactly what I am proposing with the only caveat that the rows are right on top of each other and not slightly shifted to the right like they would be on a normal keyboard.

**Comment by flipcoder** [comment]
I'm not an expert with ergonomics so I can't really say if something is better.  The chords are easier to hold for me and the motion seems smoother for most things I play, but I can only speculate how that translates long term.  I would be very surprised if it ends up being worse though.

**Comment by flipcoder** [comment]
And yes once I have custom layouts available you should be able to do the one you're talking about

**Comment by martinmr** [comment]
Looks better than the default one for sure, but I lose easy chromaticism, which I don't really want to give up since they are very useful for the kind of music I like playing.

Looking forward to custom layouts then, I'll try it out.

**Comment by flipcoder** [comment]
Yeah, chromaticism on this layout takes practice.  The chromatic scale is a diagonal 2-3 or 3-2 pattern instead, see here:

https://i.imgur.com/Fg7qmea.png

Still possible with practice but for music that makes heavy use of it it might not be the option you want.

Thanks for your comments!

**Comment by martinmr** [comment]
So in the hopes of getting you to prioritize this feature (lol), I'll share this trick I learned recently, which involves chromatic notes and why I need them.

So I bought this course: https://improviseforreal.com/ and have been working on it for a few months. Mostly in exercise 2, which contains one trick that I hadn't really figured out, even though it's so obvious from very basic knowledge of music theory. Also found the same trick described in the book "The Music Lesson" by Victor Wooten, which is very good and covers a lot more than harmony. The other course doesn't really deal with rhythm, for example, but you pick that up naturally if you follow the exercise.

So here's the trick if you want to jam along with other musicians: **just play any note**:

- If you land in the key, with 7/12 probability, then there's no issue.
- If you land outside the key, then the notes right above and below are in the key. So the "wrong" choice gives you twice the amount of information.
- This works in every mode, since the notes are the same as the ones of one major scale. So it works in pretty much any song you are likely to hear. Difficult songs just do it again when there's a change of key/mode.

In practice, this translates to not being afraid of losing the tonality of the piece. Even if you do, you simply play another note, hear if it's in or out of key, and proceed from there. So I started jamming to songs using this and quickly became very fun. I won't claim to kill it every time, but there's simply been a jump in my musicianship that felt impossible when I practiced with other methods. Because I am practicing the actual thing that I want to learn. Not scales, or sight-singing, or theory, etc. Not that I won't try to learn them eventually, but because now I have a handle on the music that I didn't before, so they are secondary.

It's also a lot of fun, so I don't even think of it as practicing. There's no dichotomy between practice and play. If I want to study a song more in depth, just load it into a specialized music player called transcribe, which lets me loop, transpose, and slow down sections of the song. Then just play over it repeatedly and figure out what sounds good and repeat it to get it into my brain. It's really about getting the underlying patterns into your mind and body. Writing it down and getting it note for note can come later, but I don't think they are required for every piece.

So a few months ago I would have loved the fact that I was less likely to hit one of them, but now they are my bread and butter.

PS: Closing the issue after posting, since it doesn't give me the option to post without reopening. No issue on my end, just one cool trick for jamming.

**Comment by flipcoder** [comment]
I should revise what I said a bit because it might cause confusion.  It's not actually hard to play chromatically on this layout.  I think I might be misleading people a bit if I say it's "harder".  What I mean is the distance for a half step is over two and up one, which is the same distance of other notes on other layouts that you'll have to play as well.  But the note after that one is just the next note to your right.  What makes it different is you have to play the chromatic scale shape backwards if you run it like a scale.  This is still easier than other things you are expected to learn on most instruments, including being less of the distance you have to hold for most chords, so I'm not sure it's even a disadvantage, just different.  You can try it on your linnstrument by holding a note and then go left 2 and up one.  Then go to the right from the original note one space.  That's 3 half steps and it's not a big distance.  You'd use three notes like this if you were using the blues scale for instance.

As for the approach you're talking about I've heard Victor Wooten say something similar.  By starting with a passing tone you can hit the next nearest note and it can sound good.  It's introducing the idea that there aren't necessarily wrong notes unless you stop there.  What sounds good in music is more about change over time instead of where you are at any point.  It's probably best that it's not done using randomness though but it can be a good approach for changing the way you approach improv and writing.  Less useful in playing a particular piece correctly but can get someone over the fear of hitting a wrong note.

I have a number of things on the TODO and fortunately you're not the only one who has recommended different layouts, so that's definitely coming!  Thanks for sharing the resource!

**Comment by flipcoder** [comment]
I got custom layouts working but it still needs some tweaking.  Have not pushed any changes yet.

![custom_layouts](https://github.com/flipcoder/midimech/assets/297665/449a0675-14fc-408b-8246-702f947ca836)

**Comment by zass30** [comment]
That's the janko layout! I'm really interested in this feature, as well as the midpoint between this and midimech -- where the sharps are diagonally up and to the left.
